language: node_js
cache:
  directories: node_modules
node_js:
  - '6'

notifications:
  slack:
    secure: m87VvXVB4ziRfYeeWmlja1eIAY8Ex3kYv27ktsbZYqX+ymIHPJN/eMazx0SL/aETCaRycPG1E7pP7CCIl93RpATMKVu5CF5L4fcMxlnBImBXMmY1PM0rMHlXSZVhjFLdRlECFO3McZB9wiRskPBsPjMtGGG6ucG2vbqoXlWJ6kzBk2zwRuwDJDrYPKEmML+L1FBOVV3/JTB67cNBz/RHjfOpTM++Oala8MIv6d5+wI7La3bcNKl5fAAmnfcg5O2NDNWg8fk+0lov56UAkWHmMMzxHnYB2RHmS9XD+VX7hBbjeQ4czKghdz+lsj3JjanTYCi2IzSJwevRnnpFXlqAi4DKitHWojA3y0w3nPbq72NGPVQG9hAFu+bOHODfzJBDAQBULZtqx1jawuQmFyiAGR+A8jYAMEbx0PgY3WAqZznL87Cdy/QMYHkn2/7zImx6fwm580jaZJJPh+R5IZEffnSGQr+mTIoDN4dfid4fBwFENoTfUyPeOp3VutvV14VSm67GjFh8lPVZWZMUk9JiS8cT/Ga013lNITQCJGblqQK3xrTcdUfy9zMB4aGhAwskdszQwRXEi/7vfrkUvd6Tu0NgBct8w/rS5TGXrdZqnT4Z9VS3qTOetbQe13LH26LONQb2PfgrlMp5zLqPrAl79fWRxHY3gsYne9I+hAHY9AA=

sudo: required

services:
  - docker

install:
  - docker build -t floq .
  - docker run -d -p 127.0.0.1:80:80 floq 
  - docker ps -a
  
after_success:
  - if [ "$TRAVIS_BRANCH" == "feature/travis-support" ]; then
    docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker tag floq floq:latest blankoslo/floq:latest
    docker push blankoslo/floq:latest
    fi