language: node_js
cache:
  directories: node_modules
node_js:
- '6'
notifications:
  slack:
    secure: JJGp2GrCqvDFrGWqNl/9AW4nCQhpE/QQ/vifuwd+I+3AiaDVZsiOzspFybhGFurovuU4dbW9RdgDr4FBe2ljwR7R2Shdz5iKPlVnayqIcwi9ZWIzxFr2Egq3R0Jfh/b5k0dQuCe3dmr5IXAjxumQoFW+IOpx4GPTZFaGwBrU5gFR6PROsztRtYaTXQA4+NiWg9T5mfJRqQLa27vjlX/OabaZlm2m30c8gIufsvazNox9rnpHjNq8aj036op/gnQveHQf5kVJjOc2/E26dWdAQKKV5GY926iCUYgjs3kJXAtNZpePGz+430Jsjq3b5Bn29t0t78Wue8R/i4jc47TKB4ydlSljndXokh2F6RW6jomMBi1VRLhcKENo9zIxBSMa+JzfoHuEZld5OrARAxueTQZigGdAnQPCQcMSIMGQap8SVkRw+x68Iv7zvFMPqozOeITn3ukEtXqea6KSWA76wuf5notDgCmOt+kCdefDxAF9LPFCib/uXbi/caLBxCx9be7cxYeRZ/yznzGNZmgexBQykvE2TYgPa+e+G8qnbS2JHrhNEaEuZhrIXp6EfU80dUQWrisTc+DfAjBuf18LbXcWMkf+ldVlWjcVXidcE4mGKSwa4M81yNKZmuN8JHVIbCQ0t40VUGd+qnxtowcgHNWRnlwrH9x8/rJHNc2qzZI=
sudo: required
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_c8fe184f3cab_key -iv $encrypted_c8fe184f3cab_iv
  -in deployment/client-secret.json.enc -out client-secret.json -d
- deployment/setup_gcloud
install:
- docker build -t floq .
- docker run -d -p 127.0.0.1:3000:3000 floq
- docker ps -a
after_success:
- deployment/deploy
env:
  matrix:
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
  global:
  - secure: m6XYoLYq4rgRYuGwJgTFebtYBShCw8Lq8/56tUVbKyI3gnyoiqvP2KBIJvKCDCESXJAOuSn7fRSb238fURL2DPOcD+e23KfLhDbNzGfi9TVWt04BrtvQsOiAMqoLpHoVsa55pjUk6MoPfn9ZSX6wTG9g0QgfN44zQ7Ncuj6JWh0Rd/rE87ujrJ7qt0iB4Bw1KrJtnqFvijWocghMkCSgEsidJY+4Ar0s/1ZS+aMZaClNSwn2iYBbkvsWHIeHA3GhYdgMZa3lfF3eHWvkkUcs+W1Dz7TGSEGLs+mG9JOb8whwDdb9Y73k++0EyqPcIQMFX+Eje9le/YXiZkSwWmxuIpTBfcPMbPhGj0UQiVkRU5wuXwyKLJ4IMlY/UKZj6hIOqWOCWx0kLxaEg8nAvMxhvuGhwYE3BQLc4lNV+yPhWIqcNy15Lm/gd+3lsUn2OQkNPQI+POUd+LEhH2Y5OFwbtG6SrnQXioRp33i+UGXm2MEVVPEDBxPOvQmISuf6iJnZwjN0rwwmwXIhHLHcRoEhRB/pVcegdl6CFU2V2EpXCsnEWPdfx/VtjktcY/W3HsXEaOnTc3t7lf9go3Rx52kcp1bGmPkBfm9GEqHvLzGscHnP9N+M69Ps4YrU7BAgE0zR/p+yJp6gGv5Q31UI0pIiop5LnXEokem+W4YgxxYouAo=
  - secure: AWionJMrb/eoL8j2/+OXR7Kmon13WNcKvXWf+fhObmpK/5bcTgrwVzu7WMZJ/IygSY/Ba/Sq/WzLhFnsGZNP8GVqBhUFUtMW3F315cIOF+jdWh9VbtOentibktKxolkYShHxXm3qDXgykV5sQ5XvJlBSo4u4cRpU+rp18UvCXp9jNIyEWcjPUbT/5+YdYsytsxZH/P0tRkEHFiPSiaUHC5uEXHalgXW5Y5OOAYUr9PeirmcRFIoWLlXLObNY/k5JMukhKkE3qkDW2MEzZ9OEkPtfij4bsbvcRknkgInfXZyRwei7EVY82pttIUUxc+cTJdvY8IWuo2nBcOPu3Bpmag1xoHoeHLuYeKpiQEAfuzKLB2M6KOSnnpZP5u+cMLbHd9qb7Mq+LXL8WgNH09VZnQMC0jCGgrQchjCxtgTFNAquirbtz7QCt6tXxo1WRJ12cyrc75vFRNMIihA5uEsGhsno+hse+tUIjFciubr9CteGByY4voiLoyHFn8AgdaKYQdKpsvR3AAwfGh+uRpKzF10ulcDMfEu5w4tolWYa41HdqvUo5/6iwrZzERsJTwBprmGgCHsZQM7Sz6+00t2N0iWrzkaV7JX0Cr3ACj9qBdakPeTJU2iE36wrE+5Na2W2uheYOKEFpP2u9EQ1esk/2uiVnh8HV/gNuAlC1hK78yY=
